[tool.ruff]
line-length = 120
extend-exclude = ["*/PalletWithSyntaxErrors.py"]
[tool.ruff.lint]
ignore = ["E501"]
[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests", "src"]
norecursedirs = [".env", "data", ".github", ".vscode"]
console_output_style = "count"
addopts = "--cov-branch --cov=projectname --cov-report term --cov-report xml:cov.xml --instafail -p no:faulthandler"
