name: Pull Request Events

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  test-unit:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Set up code
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          cache: pip
          cache-dependency-path: setup.py

      - name: 📥 Install arcgis dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libkrb5-dev

      - name: 🏗 Install module
        run: pip install .[tests]

      - name: 🧶 Lint
        run: ruff check --output-format=github .

      - name: ⬆️ Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./cov.xml
